# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa8f3f43376cdcb2ad81bfa84e491abfb347f48bf6a8171a1d17d35f29e1c1a4f509815f58a6eff254c14b76db6aa7feb361ddae3889be8b51390d5be6e8c72d

test:
  secret_key_base: 2dc76fe5d5c33bd111845ad656e7eafc0c222258976acea47479ef10af64b7d68007f7410ca6fc1d5d83145fdccb72ade5aadb009dfcd5039917844427a7e5c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
